apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: edb-postgres
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: app-db-credentials
  storage:
    size: 10Gi
    storageClass: topolvm-provisioner
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
