---
galaxy_info:
  author: EDB Operations Team
  description: Integrate AAP cluster management with EDB Failover Manager
  company: EnterpriseDB
  license: BSD-3-Clause
  min_ansible_version: "2.11"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - aap
    - ansible
    - automation
    - efm
    - failover
    - postgres
    - postgresql
    - disaster_recovery
    - integration

dependencies: []
