---
galaxy_info:
  role_name: deploy_dr_replica
  author: EDB Engineering Team
  description: Deploy a DR replica cluster (distributed topology, symmetric architecture)
  company: EnterpriseDB
  license: Apache-2.0
  min_ansible_version: "2.14"
  galaxy_tags:
    - postgresql
    - replica
    - disaster_recovery
    - openshift
    - edb

dependencies: []
