---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dr-test-service-account
  namespace: edb-postgres
  labels:
    app: dr-testing

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dr-test-cluster-role
  labels:
    app: dr-testing
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - endpoints
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch

  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - replicasets
    verbs:
      - get
      - list
      - watch
      - update
      - patch

  - apiGroups: ["postgresql.cnpg.io"]
    resources:
      - clusters
    verbs:
      - get
      - list
      - watch
      - update
      - patch

  - apiGroups: ["route.openshift.io"]
    resources:
      - routes
    verbs:
      - get
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dr-test-cluster-role-binding
  labels:
    app: dr-testing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dr-test-cluster-role
subjects:
  - kind: ServiceAccount
    name: dr-test-service-account
    namespace: edb-postgres
